- name: Main file
  hosts: all
  connection: local 
  gather_facts: true
  become: true
  vars_files:
    - vars/main.yaml
  roles:
    - role: adduser-role
    - role: general_settings-role
    - role: sshd-role
    - role: chrony-role
    - role: mariadb-role
    - role: cron-role
    - role: sysctl-role
    - role: AIDE-role
  tasks:
    - name: Sshd
      ansible.builtin.include_role:
        name: sshd-role
        tasks_from: restart_sshd.yaml 

