name: Terraform Deploy (All Accounts)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  management:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC (Management)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238407199949:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (Management)
        working-directory: Management                 # << ROOT DIR for Prod stack
        run: terraform init -input=false

      - name: Terraform Plan (Management)
        working-directory: Management
        run: terraform plan -input=false

      - name: Terraform Apply (Management, only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: Management
        run: terraform apply -auto-approve -input=false


  network:
    runs-on: ubuntu-latest
    needs: management
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC (Management)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238407199949:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (Network)
        working-directory: NetworkSecurity       # << ROOT DIR for Network stack
        run: terraform init -input=false

      - name: Terraform Plan (Network)
        working-directory: NetworkSecurity
        run: terraform plan -input=false

      - name: Terraform Apply (Network, only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: NetworkSecurity
        run: terraform apply -auto-approve -input=false


  dev:
    runs-on: ubuntu-latest
    needs: network             # optional: wait for network job
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC (Management)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238407199949:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (Dev)
        working-directory: Dev                  # << ROOT DIR for Dev stack
        run: terraform init -input=false

      - name: Terraform Plan (Dev)
        working-directory: Dev
        run: terraform plan -input=false

      - name: Terraform Apply (Dev, only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: Dev
        run: terraform apply -auto-approve -input=false


  prod:
    runs-on: ubuntu-latest
    needs: network      # optional: only after those
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC (Management)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238407199949:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (Prod)
        working-directory: Prod                 # << ROOT DIR for Prod stack
        run: terraform init -input=false

      - name: Terraform Plan (Prod)
        working-directory: Prod
        run: terraform plan -input=false

      - name: Terraform Apply (Prod, only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: Prod
        run: terraform apply -auto-approve -input=false


  security:
    runs-on: ubuntu-latest
    needs: prod      # optional: only after those
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC (Management)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238407199949:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (Security)
        working-directory: Security                 # << ROOT DIR for Prod stack
        run: terraform init -input=false

      - name: Terraform Plan (Security)
        working-directory: Security
        run: terraform plan -input=false

      - name: Terraform Apply (Security, only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: Security
        run: terraform apply -auto-approve -input=false

