name: Terraform Destroy Stage1 (All Accounts)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  management:
    runs-on: ubuntu-latest
    needs: network
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC (Management)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238407199949:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3


      - name: Terraform Apply (Management, only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: Management/Stage1
        run: terraform destroy -auto-approve -input=false


  network:
    runs-on: ubuntu-latest
    needs: prod
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC (Network)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238407199949:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply (Network, only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: Network/Stage1 
        run: terraform destroy -auto-approve -input=false


  prod:
    runs-on: ubuntu-latest
    needs: security      # optional: only after those
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC (Production)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238407199949:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply (Prod, only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: Prod/Stage1 
        run: terraform destroy -auto-approve -input=false


  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC (Security)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238407199949:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply (Security, only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: Security/Stage1 
        run: terraform destroy -auto-approve -input=false
